---
Name: betterbuttons
---
SilverStripe\ORM\DataObject:
  extensions:
    - UncleCheese\BetterButtons\Extensions\BetterButtons
SilverStripe\Forms\GridField\GridFieldDetailForm:
  extensions:
    - UncleCheese\BetterButtons\Extensions\BetterButtonsGridFieldDetailForm

UncleCheese\BetterButtons\Extensions\BetterButtons:
  utils:
    edit:
      prevNext: true
      create: true
    versioned_edit:
      prevNext: true
      create: true
    create:
      create: true
  actions:
    create:
      save: true
      saveAndClose: true
    edit:
      save: true
      saveAndClose: true
      delete: true
      frontendLinks: true
    versioned_edit:
#      saveAndAdd: true
#      saveAndNext: true
#      saveAndPrev: true
#      saveAndClose: true
      group:
        label: Versioning...
        buttons:
          rollback: true
      frontendLinks: true
---
Only:
  moduleexists: silverstripe/userforms
---
SilverStripe\UserForms\Model\EditableFormField:
  better_buttons_versioned_enabled: false
SilverStripe\UserForms\Model\EditableFormField\EditableOption:
  better_buttons_versioned_enabled: false
